import React, { useState, useEffect } from 'react';
import { 
  Copy, 
  Check, 
  Search, 
  Eye, 
  Code, 
  Zap, 
  Shield, 
  FileText, 
  Tag, 
  Globe,
  Smartphone,
  Facebook,
  Twitter,
  Linkedin,
  Instagram,
  AlertCircle,
  TrendingUp,
  BarChart,
  HelpCircle,
  Download,
  Share2,
  Sparkles,
  RefreshCw,
  ExternalLink
} from 'lucide-react';
import { ToolNavigation } from '../components/ToolNavigation';

export const MetaGenerator: React.FC = () => {
  const [meta, setMeta] = useState({
    title: 'Boost Your SEO: Free Online Meta Tag Generator Tool 2026',
    description: 'Generate perfect meta tags instantly with our free online meta generator. No signup required. Optimize title, description & keywords for better SEO rankings.',
    keywords: 'free online meta generator, SEO meta tag generator tool, meta title and description generator, google meta tags, instant html meta generator, website meta tag builder',
    author: 'The Web Toolskit',
    robots: 'index, follow',
    ogTitle: '',
    ogDescription: '',
    ogImage: '',
    twitterCard: 'summary_large_image',
    twitterSite: '@webtoolskit',
    canonicalUrl: 'https://thewebtoolskit.com/meta-generator',
    viewport: 'width=device-width, initial-scale=1.0',
    charset: 'UTF-8'
  });

  const [characterCounts, setCharacterCounts] = useState({
    title: 0,
    description: 0,
    keywords: 0
  });

  const [activeTab, setActiveTab] = useState('google');
  const [copied, setCopied] = useState(false);
  const [downloaded, setDownloaded] = useState(false);
  const [shared, setShared] = useState(false);
  const [showFAQs, setShowFAQs] = useState(false);

  // Calculate character counts
  useEffect(() => {
    setCharacterCounts({
      title: meta.title.length,
      description: meta.description.length,
      keywords: meta.keywords.length
    });
  }, [meta]);

  // Generate comprehensive HTML output
  const generatedHtml = `<!-- Generated by The Web Toolskit Meta Generator -->
<!-- Primary Meta Tags -->
<title>${meta.title}</title>
<meta name="description" content="${meta.description}">
<meta name="keywords" content="${meta.keywords}">
<meta name="author" content="${meta.author}">
<meta name="robots" content="${meta.robots}">

<!-- Viewport & Charset -->
<meta charset="${meta.charset}">
<meta name="viewport" content="${meta.viewport}">

<!-- Canonical URL -->
<link rel="canonical" href="${meta.canonicalUrl}">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="${meta.canonicalUrl}">
<meta property="og:title" content="${meta.ogTitle || meta.title}">
<meta property="og:description" content="${meta.ogDescription || meta.description}">
${meta.ogImage ? `<meta property="og:image" content="${meta.ogImage}">` : ''}
<meta property="og:site_name" content="The Web Toolskit">

<!-- Twitter -->
<meta property="twitter:card" content="${meta.twitterCard}">
<meta property="twitter:url" content="${meta.canonicalUrl}">
<meta property="twitter:title" content="${meta.ogTitle || meta.title}">
<meta property="twitter:description" content="${meta.ogDescription || meta.description}">
${meta.ogImage ? `<meta property="twitter:image" content="${meta.ogImage}">` : ''}
<meta property="twitter:site" content="${meta.twitterSite}">

<!-- Additional Meta Tags -->
<meta name="theme-color" content="#4f46e5">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="generator" content="The Web Toolskit Meta Generator">`;

  // FIXED: Copy function
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generatedHtml);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
      // Fallback for older browsers
      const textArea = document.createElement('textarea');
      textArea.value = generatedHtml;
      document.body.appendChild(textArea);
      textArea.select();
      document.execCommand('copy');
      document.body.removeChild(textArea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  // FIXED: Download as HTML file
  const handleDownload = () => {
    const element = document.createElement('a');
    const file = new Blob([generatedHtml], {type: 'text/html'});
    element.href = URL.createObjectURL(file);
    element.download = 'meta-tags.html';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
    
    setDownloaded(true);
    setTimeout(() => setDownloaded(false), 2000);
  };

  // FIXED: Share configuration
  const handleShare = () => {
    const config = {
      title: meta.title,
      description: meta.description.substring(0, 100) + '...',
      keywords: meta.keywords.split(',').slice(0, 3).join(', '),
      url: window.location.href
    };
    
    const shareText = `Check out these meta tags I created with The Web Toolskit Meta Generator:\nTitle: ${config.title}\nDescription: ${config.description}\nKeywords: ${config.keywords}\n\nGenerate your own at: ${config.url}`;
    
    if (navigator.share) {
      navigator.share({
        title: 'Meta Tags Configuration',
        text: shareText,
        url: config.url
      }).catch(console.error);
    } else {
      navigator.clipboard.writeText(shareText);
      setShared(true);
      setTimeout(() => setShared(false), 2000);
    }
  };

  const handleReset = () => {
    setMeta({
      title: 'Boost Your SEO: Free Online Meta Tag Generator Tool 2026',
      description: 'Generate perfect meta tags instantly with our free online meta generator. No signup required. Optimize title, description & keywords for better SEO rankings.',
      keywords: 'free online meta generator, SEO meta tag generator tool, meta title and description generator, google meta tags, instant html meta generator, website meta tag builder',
      author: 'The Web Toolskit',
      robots: 'index, follow',
      ogTitle: '',
      ogDescription: '',
      ogImage: '',
      twitterCard: 'summary_large_image',
      twitterSite: '@webtoolskit',
      canonicalUrl: 'https://thewebtoolskit.com/meta-generator',
      viewport: 'width=device-width, initial-scale=1.0',
      charset: 'UTF-8'
    });
  };

  const seoChecklist = [
    {
      label: 'Title length optimal (50-60 chars)',
      passed: characterCounts.title >= 50 && characterCounts.title <= 60,
      current: `${characterCounts.title}/60`,
      importance: 'high'
    },
    {
      label: 'Description length optimal (150-160 chars)',
      passed: characterCounts.description >= 150 && characterCounts.description <= 160,
      current: `${characterCounts.description}/160`,
      importance: 'high'
    },
    {
      label: 'Title contains primary keyword',
      passed: meta.title.toLowerCase().includes('meta') || meta.title.toLowerCase().includes('seo'),
      current: '✓',
      importance: 'high'
    },
    {
      label: 'Description contains keywords',
      passed: meta.description.split(' ').length > 20,
      current: `${meta.description.split(' ').length} words`,
      importance: 'medium'
    },
    {
      label: 'Keywords properly formatted',
      passed: meta.keywords.includes(',') && meta.keywords.split(',').length >= 3,
      current: `${meta.keywords.split(',').length} keywords`,
      importance: 'medium'
    },
    {
      label: 'No duplicate content',
      passed: meta.title !== meta.description,
      current: '✓',
      importance: 'low'
    }
  ];

  // Enhanced FAQs with more keywords
  const faqs = [
    {
      question: 'Why are meta tags important for SEO rankings?',
      answer: 'Meta tags help search engines understand your page content, improve click-through rates in SERPs, and enhance social media sharing. Properly optimized meta tags with relevant keywords can significantly boost your organic search rankings and user engagement. Using tools like our free online meta generator ensures your title, description, and keywords are perfectly formatted for maximum SEO impact.'
    },
    {
      question: 'What is the ideal length for meta titles and descriptions in 2026?',
      answer: 'For optimal display in Google search results, meta titles should be 50-60 characters. Meta descriptions should be 150-160 characters to provide enough context without being truncated. Our meta tag generator tool automatically checks these limits and provides real-time feedback to help you create perfect meta tags for your website.'
    },
    {
      question: 'Do keywords in meta tags still matter for SEO optimization?',
      answer: 'While not as critical as before, relevant keywords in meta tags help search engines understand your content focus. Our free SEO meta description tool helps you include keywords naturally without stuffing. Focus on user-focused language that includes your target keywords organically for the best on-page SEO results.'
    },
    {
      question: 'How does this free online meta generator differ from other tools?',
      answer: 'Our tool is 100% free with no registration required, processes everything locally in your browser for maximum privacy, includes social media meta tags (Open Graph & Twitter Cards), provides real-time previews across all platforms, and offers comprehensive SEO analysis with actionable recommendations. Unlike other tools, we don\'t limit features or require signups.'
    },
    {
      question: 'Can I use this meta tag generator for bulk meta tag creation?',
      answer: 'Yes! You can generate multiple meta tags by saving different configurations. For bulk processing, create templates and modify them for different pages. Our website meta tag builder is perfect for bloggers, developers, and SEO professionals who need to optimize multiple pages quickly.'
    },
    {
      question: 'Is this tool mobile-friendly and browser-based?',
      answer: 'Absolutely! Our instant HTML meta generator works perfectly on all devices and browsers. Since it\'s a browser-based meta tool, there are no downloads required. Everything processes locally, making it fast, secure, and accessible from any device with an internet connection.'
    }
  ];

  // Expanded popular keywords list
  const popularKeywords = [
    'free online meta generator',
    'SEO meta tag generator tool',
    'meta title and description generator',
    'free google meta tag generator',
    'easy meta generator for websites',
    'instant html meta generator',
    'free seo meta description tool',
    'generate meta tags online free',
    'website meta tag builder',
    'online meta tag creator',
    'best free meta generator 2026',
    'meta keywords generator tool',
    'on-page seo meta tool',
    'simple meta tag generator online',
    'no signup meta generator',
    'social media meta tag generator',
    'free automatic meta tag tool',
    'bulk meta tag generator',
    'meta tag generator for blog posts',
    'browser-based meta tool',
    'open graph meta generator',
    'twitter card generator',
    'seo optimization tools',
    'meta tags for better ranking',
    'mobile-friendly meta tags',
    'seo meta tags 2026',
    'google search meta tags',
    'facebook open graph generator',
    'meta tag analyzer tool',
    'seo title tag generator',
    'meta description checker',
    'html meta tags generator',
    'free seo tool for meta',
    'professional meta tag creator',
    'meta tags for ecommerce',
    'blog meta tag generator',
    'website seo meta generator',
    'responsive meta tag tool',
    'schema markup generator',
    'structured data meta tags'
  ];

  return (
    <div className="max-w-7xl mx-auto space-y-8 animate-in slide-in-from-bottom-4 duration-500">
      {/* Hero Header */}
      <div className="bg-gradient-to-r from-indigo-600 to-purple-600 rounded-3xl p-8 md:p-12 text-white overflow-hidden relative">
        <div className="relative z-10">
          <div className="flex items-center gap-3 mb-4">
            <Tag className="w-8 h-8" />
            <span className="text-sm font-semibold bg-white/20 px-3 py-1 rounded-full">PREMIUM SEO TOOL</span>
          </div>
          <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-4">
            Free Online Meta Tag Generator Tool
          </h1>
          <p className="text-lg text-indigo-100 mb-6 max-w-3xl">
            Create perfect SEO-optimized meta tags instantly. Generate title, description, Open Graph, and Twitter Cards with real-time previews. No signup required. 100% free forever.
          </p>
          <div className="flex flex-wrap gap-2">
            {['100% Free Tool', 'No Registration', 'Instant Results', 'Browser-Based', 'SEO Optimized', 'Social Media Ready', 'Mobile Friendly', 'Privacy Focused'].map((badge, idx) => (
              <span key={idx} className="px-3 py-1 bg-white/10 rounded-full text-sm hover:bg-white/20 transition-colors cursor-default">
                {badge}
              </span>
            ))}
          </div>
        </div>
        <div className="absolute right-0 top-0 w-64 h-64 bg-gradient-to-l from-white/10 to-transparent rounded-full -translate-y-32 translate-x-32"></div>
      </div>

      {/* SEO Keywords Banner */}
      <div className="bg-gradient-to-r from-blue-50 to-indigo-50 p-4 rounded-2xl border border-blue-100">
        <div className="flex flex-wrap gap-2 justify-center">
          {popularKeywords.slice(0, 10).map((keyword, idx) => (
            <span key={idx} className="px-3 py-1.5 bg-white/80 hover:bg-white text-slate-700 rounded-lg text-sm font-medium transition-all hover:scale-105 cursor-default shadow-sm">
              {keyword}
            </span>
          ))}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Left Column - Editor */}
        <div className="lg:col-span-2 space-y-6">
          {/* Quick Stats */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="bg-white p-4 rounded-2xl border border-slate-100 shadow-sm hover:shadow-md transition-shadow">
              <div className="text-sm text-slate-600 mb-1">Title Score</div>
              <div className="text-2xl font-bold text-slate-900">
                {characterCounts.title >= 50 && characterCounts.title <= 60 ? 'A+' : characterCounts.title > 60 ? 'B' : 'C'}
              </div>
              <div className="text-xs text-slate-500 mt-1">{characterCounts.title}/60 chars</div>
            </div>
            <div className="bg-white p-4 rounded-2xl border border-slate-100 shadow-sm hover:shadow-md transition-shadow">
              <div className="text-sm text-slate-600 mb-1">Desc Score</div>
              <div className="text-2xl font-bold text-slate-900">
                {characterCounts.description >= 150 && characterCounts.description <= 160 ? 'A+' : characterCounts.description > 160 ? 'B' : 'C'}
              </div>
              <div className="text-xs text-slate-500 mt-1">{characterCounts.description}/160 chars</div>
            </div>
            <div className="bg-white p-4 rounded-2xl border border-slate-100 shadow-sm hover:shadow-md transition-shadow">
              <div className="text-sm text-slate-600 mb-1">Keywords</div>
              <div className="text-2xl font-bold text-slate-900">
                {meta.keywords.split(',').filter(k => k.trim()).length}
              </div>
              <div className="text-xs text-slate-500 mt-1">Total keywords</div>
            </div>
            <div className="bg-white p-4 rounded-2xl border border-slate-100 shadow-sm hover:shadow-md transition-shadow">
              <div className="text-sm text-slate-600 mb-1">SEO Score</div>
              <div className="text-2xl font-bold text-slate-900">
                {Math.round((seoChecklist.filter(item => item.passed).length / seoChecklist.length) * 100)}%
              </div>
              <div className="text-xs text-slate-500 mt-1">Optimization</div>
            </div>
          </div>

          {/* Meta Editor */}
          <div className="bg-white rounded-2xl border border-slate-100 shadow-lg overflow-hidden">
            <div className="p-6 border-b border-slate-100 bg-gradient-to-r from-slate-50 to-white">
              <div className="flex justify-between items-center">
                <h2 className="text-xl font-bold text-slate-900 flex items-center gap-2">
                  <FileText className="w-5 h-5" />
                  Meta Tag Editor
                </h2>
                <button
                  onClick={handleReset}
                  className="text-sm px-4 py-2 text-slate-600 hover:text-slate-900 hover:bg-slate-50 rounded-lg transition-colors flex items-center gap-2"
                >
                  <RefreshCw className="w-4 h-4" />
                  Reset
                </button>
              </div>
            </div>

            <div className="p-6 space-y-6">
              {/* Title */}
              <div className="space-y-3">
                <div className="flex justify-between items-center">
                  <label className="text-sm font-semibold text-slate-900 flex items-center gap-2">
                    <Tag className="w-4 h-4" />
                    Page Title
                  </label>
                  <span className={`text-sm font-medium ${characterCounts.title >= 50 && characterCounts.title <= 60 ? 'text-green-600' : 'text-amber-600'}`}>
                    {characterCounts.title}/60 characters
                  </span>
                </div>
                <input
                  type="text"
                  value={meta.title}
                  onChange={e => setMeta({...meta, title: e.target.value})}
                  className="w-full p-4 border border-slate-200 rounded-xl focus:ring-2 focus:ring-indigo-200 focus:border-indigo-500 focus:outline-none transition-all text-lg"
                  placeholder="Enter your page title here..."
                />
                <div className="flex items-center gap-2 text-sm text-slate-600">
                  <AlertCircle className="w-4 h-4" />
                  <span>Include primary keywords like "meta generator" or "SEO tool", keep it under 60 characters, and make it compelling for click-throughs.</span>
                </div>
              </div>

              {/* Description */}
              <div className="space-y-3">
                <div className="flex justify-between items-center">
                  <label className="text-sm font-semibold text-slate-900 flex items-center gap-2">
                    <FileText className="w-4 h-4" />
                    Meta Description
                  </label>
                  <span className={`text-sm font-medium ${characterCounts.description >= 150 && characterCounts.description <= 160 ? 'text-green-600' : 'text-amber-600'}`}>
                    {characterCounts.description}/160 characters
                  </span>
                </div>
                <textarea
                  rows={3}
                  value={meta.description}
                  onChange={e => setMeta({...meta, description: e.target.value})}
                  className="w-full p-4 border border-slate-200 rounded-xl focus:ring-2 focus:ring-indigo-200 focus:border-indigo-500 focus:outline-none transition-all resize-none"
                  placeholder="Write a compelling description that includes keywords and a call-to-action..."
                />
                <div className="flex items-center gap-2 text-sm text-slate-600">
                  <AlertCircle className="w-4 h-4" />
                  <span>Include keywords naturally, summarize page content, and encourage clicks with action-oriented language. Perfect for SEO optimization.</span>
                </div>
              </div>

              {/* Keywords */}
              <div className="space-y-3">
                <div className="flex justify-between items-center">
                  <label className="text-sm font-semibold text-slate-900 flex items-center gap-2">
                    <Search className="w-4 h-4" />
                    Keywords
                  </label>
                  <span className="text-sm text-slate-600">
                    {meta.keywords.split(',').filter(k => k.trim()).length} keywords
                  </span>
                </div>
                <textarea
                  rows={2}
                  value={meta.keywords}
                  onChange={e => setMeta({...meta, keywords: e.target.value})}
                  className="w-full p-4 border border-slate-200 rounded-xl focus:ring-2 focus:ring-indigo-200 focus:border-indigo-500 focus:outline-none transition-all resize-none"
                  placeholder="free online meta generator, SEO tool, meta tag creator..."
                />
                <div className="text-sm text-slate-600">
                  <p className="mb-2 font-medium">Popular SEO keywords for meta tags:</p>
                  <div className="flex flex-wrap gap-2">
                    {popularKeywords.slice(0, 12).map((keyword, idx) => (
                      <button
                        key={idx}
                        onClick={() => {
                          const current = meta.keywords ? meta.keywords + ', ' : '';
                          setMeta({...meta, keywords: current + keyword});
                        }}
                        className="text-xs px-3 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-lg transition-colors hover:scale-105 active:scale-95"
                      >
                        + {keyword}
                      </button>
                    ))}
                  </div>
                </div>
              </div>

              {/* Advanced Settings */}
              <div className="border-t border-slate-100 pt-6">
                <h3 className="text-lg font-semibold text-slate-900 mb-4 flex items-center gap-2">
                  <Zap className="w-5 h-5" />
                  Advanced Meta Settings
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-3">
                    <label className="text-sm font-semibold text-slate-700">Open Graph Title</label>
                    <input
                      type="text"
                      value={meta.ogTitle}
                      onChange={e => setMeta({...meta, ogTitle: e.target.value})}
                      className="w-full p-3 border border-slate-200 rounded-lg focus:ring-2 focus:ring-indigo-200 focus:outline-none"
                      placeholder="Custom OG title (optional)"
                    />
                  </div>
                  <div className="space-y-3">
                    <label className="text-sm font-semibold text-slate-700">Canonical URL</label>
                    <input
                      type="text"
                      value={meta.canonicalUrl}
                      onChange={e => setMeta({...meta, canonicalUrl: e.target.value})}
                      className="w-full p-3 border border-slate-200 rounded-lg focus:ring-2 focus:ring-indigo-200 focus:outline-none"
                      placeholder="https://thewebtoolskit.com/your-page"
                    />
                  </div>
                  <div className="space-y-3">
                    <label className="text-sm font-semibold text-slate-700">OG Image URL</label>
                    <input
                      type="text"
                      value={meta.ogImage}
                      onChange={e => setMeta({...meta, ogImage: e.target.value})}
                      className="w-full p-3 border border-slate-200 rounded-lg focus:ring-2 focus:ring-indigo-200 focus:outline-none"
                      placeholder="https://thewebtoolskit.com/image.jpg"
                    />
                  </div>
                  <div className="space-y-3">
                    <label className="text-sm font-semibold text-slate-700">Robots Directive</label>
                    <select
                      value={meta.robots}
                      onChange={e => setMeta({...meta, robots: e.target.value})}
                      className="w-full p-3 border border-slate-200 rounded-lg focus:ring-2 focus:ring-indigo-200 focus:outline-none bg-white"
                    >
                      <option value="index, follow">Index, Follow</option>
                      <option value="noindex, nofollow">No Index, No Follow</option>
                      <option value="index, nofollow">Index, No Follow</option>
                      <option value="noindex, follow">No Index, Follow</option>
                    </select>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Generated HTML Output */}
          <div className="bg-slate-900 rounded-2xl shadow-xl overflow-hidden">
            <div className="p-6 border-b border-slate-800 bg-gradient-to-r from-slate-800 to-slate-900">
              <div className="flex justify-between items-center">
                <div className="flex items-center gap-3">
                  <Code className="w-5 h-5 text-blue-300" />
                  <span className="text-white font-semibold">Generated HTML Meta Tags</span>
                </div>
                <button
                  onClick={handleCopy}
                  className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg transition-colors flex items-center gap-2"
                >
                  {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                  {copied ? 'Copied!' : 'Copy HTML'}
                </button>
              </div>
            </div>
            <div className="p-6">
              <pre className="text-blue-300 text-sm overflow-x-auto font-mono whitespace-pre-wrap leading-relaxed bg-slate-800/50 p-4 rounded-lg">
                {generatedHtml}
              </pre>
              <div className="mt-4 flex items-center gap-2 text-sm text-slate-400">
                <Shield className="w-4 h-4" />
                <span>Your data is processed locally in your browser. No data is sent to our servers. 100% private.</span>
              </div>
            </div>
          </div>
        </div>

        {/* Right Column - Previews & Analysis */}
        <div className="space-y-6">
          {/* Preview Tabs */}
          <div className="bg-white rounded-2xl border border-slate-100 shadow-lg overflow-hidden">
            <div className="border-b border-slate-100">
              <div className="flex">
                {['google', 'facebook', 'twitter', 'mobile'].map((tab) => (
                  <button
                    key={tab}
                    onClick={() => setActiveTab(tab)}
                    className={`flex-1 py-3 text-sm font-medium transition-colors ${
                      activeTab === tab
                        ? 'text-indigo-600 border-b-2 border-indigo-600'
                        : 'text-slate-600 hover:text-slate-900'
                    }`}
                  >
                    <div className="flex items-center justify-center gap-2">
                      {tab === 'google' && <Globe className="w-4 h-4" />}
                      {tab === 'facebook' && <Facebook className="w-4 h-4" />}
                      {tab === 'twitter' && <Twitter className="w-4 h-4" />}
                      {tab === 'mobile' && <Smartphone className="w-4 h-4" />}
                      {tab.charAt(0).toUpperCase() + tab.slice(1)}
                    </div>
                  </button>
                ))}
              </div>
            </div>

            <div className="p-6">
              {activeTab === 'google' && (
                <div className="space-y-3">
                  <div className="text-sm text-slate-500">thewebtoolskit.com</div>
                  <h3 className="text-[#1a0dab] text-xl font-normal hover:underline cursor-pointer leading-snug">
                    {meta.title}
                  </h3>
                  <div className="text-green-700 text-sm">https://thewebtoolskit.com › meta-generator</div>
                  <p className="text-[#4d5156] text-sm leading-relaxed">
                    {meta.description}
                  </p>
                </div>
              )}

              {activeTab === 'facebook' && (
                <div className="border border-slate-200 rounded-lg overflow-hidden">
                  <div className="bg-gray-50 p-3 border-b border-slate-200">
                    <div className="flex items-center gap-2">
                      <Facebook className="w-4 h-4 text-blue-600" />
                      <span className="text-sm font-medium">Facebook Preview</span>
                    </div>
                  </div>
                  <div className="p-4">
                    <div className="text-sm text-blue-600 mb-1">thewebtoolskit.com</div>
                    <h4 className="font-semibold text-slate-900 mb-2">{meta.ogTitle || meta.title}</h4>
                    <p className="text-sm text-slate-600 mb-3">
                      {meta.ogDescription || meta.description}
                    </p>
                    {meta.ogImage && (
                      <div className="bg-slate-100 h-48 rounded-lg flex items-center justify-center text-slate-400">
                        <Eye className="w-8 h-8" />
                      </div>
                    )}
                  </div>
                </div>
              )}

              {activeTab === 'twitter' && (
                <div className="border border-slate-200 rounded-lg overflow-hidden">
                  <div className="bg-gray-50 p-3 border-b border-slate-200">
                    <div className="flex items-center gap-2">
                      <Twitter className="w-4 h-4 text-blue-400" />
                      <span className="text-sm font-medium">Twitter Card Preview</span>
                    </div>
                  </div>
                  <div className="p-4">
                    <div className="text-sm text-slate-500 mb-1">@webtoolskit</div>
                    <h4 className="font-bold text-slate-900 mb-2">{meta.ogTitle || meta.title}</h4>
                    <p className="text-sm text-slate-600 mb-3">
                      {meta.ogDescription || meta.description}
                    </p>
                    {meta.ogImage && (
                      <div className="bg-slate-100 h-48 rounded-lg flex items-center justify-center text-slate-400">
                        <Eye className="w-8 h-8" />
                      </div>
                    )}
                  </div>
                </div>
              )}

              {activeTab === 'mobile' && (
                <div className="border-2 border-slate-200 rounded-xl p-4 mx-auto" style={{ maxWidth: '320px' }}>
                  <div className="flex items-center justify-between mb-3">
                    <div className="text-sm font-semibold text-slate-900 truncate">
                      {meta.title.substring(0, 30)}...
                    </div>
                    <div className="text-xs text-slate-500">•••</div>
                  </div>
                  <div className="text-xs text-slate-600 mb-4 line-clamp-3">
                    {meta.description.substring(0, 120)}...
                  </div>
                  <div className="text-xs text-green-700">thewebtoolskit.com</div>
                </div>
              )}
            </div>
          </div>

          {/* SEO Analysis */}
          <div className="bg-white rounded-2xl border border-slate-100 shadow-lg overflow-hidden">
            <div className="p-6 border-b border-slate-100 bg-gradient-to-r from-slate-50 to-white">
              <h3 className="text-lg font-semibold text-slate-900 flex items-center gap-2">
                <TrendingUp className="w-5 h-5" />
                SEO Analysis
              </h3>
              <p className="text-sm text-slate-600 mt-1">
                Real-time feedback on your meta tags
              </p>
            </div>
            <div className="p-6">
              <div className="space-y-4">
                {seoChecklist.map((item, index) => (
                  <div key={index} className="flex items-start gap-3">
                    <div className={`mt-0.5 ${item.passed ? 'text-green-500' : 'text-amber-500'}`}>
                      {item.passed ? <Check className="w-5 h-5" /> : <AlertCircle className="w-5 h-5" />}
                    </div>
                    <div className="flex-1">
                      <div className="flex justify-between items-center">
                        <span className={`font-medium ${item.passed ? 'text-slate-900' : 'text-slate-700'}`}>
                          {item.label}
                        </span>
                        <span className="text-sm text-slate-500">{item.current}</span>
                      </div>
                      <div className={`mt-1 h-1.5 rounded-full ${item.passed ? 'bg-green-100' : 'bg-amber-100'}`}>
                        <div
                          className={`h-full rounded-full ${item.passed ? 'bg-green-500' : 'bg-amber-500'}`}
                          style={{ width: item.passed ? '100%' : '70%' }}
                        />
                      </div>
                    </div>
                  </div>
                ))}
              </div>
              <div className="mt-6 p-4 bg-gradient-to-r from-blue-50 to-indigo-50 rounded-xl">
                <h4 className="font-semibold text-slate-900 mb-2 flex items-center gap-2">
                  <Sparkles className="w-4 h-4" />
                  Pro Tip for Better SEO
                </h4>
                <p className="text-sm text-slate-700">
                  Include your primary keyword in the first 60 characters of your title and create unique meta descriptions for every page to maximize SEO impact. Use our free online meta generator for perfect results every time.
                </p>
              </div>
            </div>
          </div>

          {/* Quick Actions - FIXED */}
          <div className="bg-gradient-to-r from-indigo-50 to-purple-50 rounded-2xl p-6 border border-indigo-100">
            <h3 className="font-semibold text-slate-900 mb-4 flex items-center gap-2">
              <Zap className="w-5 h-5" />
              Quick Actions
            </h3>
            <div className="space-y-3">
              <button
                onClick={handleCopy}
                className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl transition-all font-medium hover:scale-[1.02] active:scale-[0.98]"
              >
                {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                {copied ? 'Copied!' : 'Copy All Meta Tags'}
              </button>
              <button
                onClick={handleDownload}
                className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-white hover:bg-slate-50 text-slate-700 border border-slate-200 rounded-xl transition-all font-medium hover:scale-[1.02] active:scale-[0.98]"
              >
                {downloaded ? <Check className="w-4 h-4" /> : <Download className="w-4 h-4" />}
                {downloaded ? 'Downloaded!' : 'Download as HTML File'}
              </button>
              <button
                onClick={handleShare}
                className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-white hover:bg-slate-50 text-slate-700 border border-slate-200 rounded-xl transition-all font-medium hover:scale-[1.02] active:scale-[0.98]"
              >
                {shared ? <Check className="w-4 h-4" /> : <Share2 className="w-4 h-4" />}
                {shared ? 'Shared!' : 'Share Configuration'}
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* SEO Content Section */}
      <div className="bg-gradient-to-br from-slate-50 to-indigo-50 rounded-3xl p-8 md:p-12 border border-slate-100">
        <div className="prose prose-lg prose-slate max-w-none">
          <h2 className="text-2xl md:text-3xl font-bold text-slate-900 mb-6">
            Why Use Our Free Online Meta Generator Tool?
          </h2>
          
          <p className="text-lg text-slate-700 mb-6">
            In the competitive landscape of <strong>SEO optimization</strong>, having perfectly crafted <strong>meta tags</strong> is crucial for better search engine rankings. Our <strong>free online meta generator</strong> provides an instant solution for creating <strong>SEO-optimized meta tags</strong> that work across all platforms including <strong>Google search results</strong>, <strong>Facebook Open Graph</strong>, and <strong>Twitter Cards</strong>.
          </p>

          <div className="grid md:grid-cols-2 gap-8 my-8">
            <div className="bg-white rounded-2xl p-6 shadow-sm hover:shadow-md transition-shadow">
              <h3 className="text-xl font-bold text-slate-900 mb-4 flex items-center gap-2">
                <BarChart className="w-5 h-5" />
                Key Features
              </h3>
              <ul className="space-y-3">
                {[
                  '100% Free - No hidden costs or limitations',
                  'No Registration Required - Start instantly',
                  'Real-time Previews - See Google, Facebook, Twitter results',
                  'Advanced SEO Analysis - Get actionable recommendations',
                  'Social Media Ready - Includes Open Graph & Twitter Cards',
                  'Mobile Optimized - Perfect for all devices',
                  'Browser-Based - No downloads, works everywhere',
                  'Privacy Focused - All processing happens locally'
                ].map((item, idx) => (
                  <li key={idx} className="flex items-start gap-3">
                    <Check className="w-5 h-5 text-green-500 flex-shrink-0 mt-0.5" />
                    <span className="text-slate-700">{item}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="bg-white rounded-2xl p-6 shadow-sm hover:shadow-md transition-shadow">
              <h3 className="text-xl font-bold text-slate-900 mb-4 flex items-center gap-2">
                <TrendingUp className="w-5 h-5" />
                SEO Benefits
              </h3>
              <ul className="space-y-3">
                {[
                  'Higher Click-Through Rates (CTR)',
                  'Improved Search Engine Rankings',
                  'Better Social Media Engagement',
                  'Increased Organic Traffic',
                  'Enhanced Brand Visibility',
                  'Mobile-Friendly Optimization',
                  'Structured Data Implementation',
                  'Competitive SEO Advantage'
                ].map((item, idx) => (
                  <li key={idx} className="flex items-start gap-3">
                    <Check className="w-5 h-5 text-green-500 flex-shrink-0 mt-0.5" />
                    <span className="text-slate-700">{item}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* FAQs - Enhanced */}
          <div className="mt-8">
            <button
              onClick={() => setShowFAQs(!showFAQs)}
              className="w-full flex items-center justify-between p-4 bg-white hover:bg-slate-50 rounded-xl transition-colors border border-slate-100"
            >
              <h3 className="text-xl font-bold text-slate-900 flex items-center gap-2">
                <HelpCircle className="w-5 h-5" />
                Frequently Asked Questions About Meta Tags & SEO
              </h3>
              <span className="text-slate-600">{showFAQs ? '▲' : '▼'}</span>
            </button>
            
            {showFAQs && (
              <div className="mt-4 space-y-4">
                {faqs.map((faq, index) => (
                  <div key={index} className="bg-white rounded-xl p-5 border border-slate-100 hover:border-indigo-200 transition-colors">
                    <h4 className="font-bold text-slate-900 mb-2">{faq.question}</h4>
                    <p className="text-slate-700">{faq.answer}</p>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* SEO Footer Keywords */}
          <div className="mt-8 p-6 bg-white rounded-2xl border border-slate-100">
            <h3 className="text-lg font-bold text-slate-900 mb-4">Popular SEO Keywords for Meta Tags</h3>
            <div className="flex flex-wrap gap-2">
              {popularKeywords.slice(15, 35).map((keyword, idx) => (
                <span key={idx} className="px-3 py-1.5 bg-slate-100 text-slate-700 rounded-lg text-sm">
                  {keyword}
                </span>
              ))}
            </div>
          </div>

          <div className="mt-8 p-6 bg-gradient-to-r from-indigo-900 to-purple-900 rounded-2xl text-white">
            <h3 className="text-xl font-bold mb-4">Ready to Boost Your SEO Rankings?</h3>
            <p className="text-indigo-100 mb-4">
              Generate perfect meta tags in seconds with our free online tool. No technical knowledge required - just enter your content and get professionally optimized meta tags instantly.
            </p>
            <div className="flex flex-wrap gap-3">
              <button
                onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
                className="px-6 py-3 bg-white text-indigo-900 font-bold rounded-xl hover:bg-slate-100 transition-all hover:scale-105 active:scale-95"
              >
                Start Generating Meta Tags
              </button>
              <a
                href="https://thewebtoolskit.com/"
                target="_blank"
                rel="noopener noreferrer"
                className="px-6 py-3 bg-indigo-700 hover:bg-indigo-800 text-white font-bold rounded-xl transition-all hover:scale-105 active:scale-95 flex items-center gap-2"
              >
                Learn More About SEO
                <ExternalLink className="w-4 h-4" />
              </a>
            </div>
            <div className="mt-4 text-sm text-indigo-300">
              Visit <a href="https://thewebtoolskit.com" className="underline hover:text-white">thewebtoolskit.com</a> for more free SEO tools and resources.
            </div>
          </div>
        </div>
      </div>

      {/* Bottom Keywords Footer */}
      <div className="bg-slate-900 text-slate-400 p-6 rounded-2xl">
        <div className="text-center">
          <p className="text-sm font-semibold mb-3">RELATED SEO KEYWORDS</p>
          <div className="flex flex-wrap justify-center gap-2">
            {popularKeywords.slice(20, 40).map((keyword, idx) => (
              <span key={idx} className="text-xs px-2 py-1 bg-slate-800 rounded hover:text-slate-300 transition-colors cursor-default">
                {keyword}
              </span>
            ))}
          </div>
          <p className="text-xs mt-4 text-slate-500">
            © {new Date().getFullYear()} The Web Toolskit - Free Online Meta Generator Tool. All tools process data locally in your browser.
          </p>
        </div>
      </div>

      <ToolNavigation />
    </div>
  );
};